### ISSUE TITLE
Add support for indexing profile create command 

### ISSUE THREAD

**Issue by reyraa** [Muzikie/service#10]
### Description
As a part of Muzikie/streamer#4, we have to update Service to support the create command of the profile module.

### Acceptance criteria
Service should be able to 
 - Index transactions of profile: create
 - List profiles 
 - Filter profiles by
    - profileID
    - creatorAddress
    - offset
    - count
- The above functionality must be tested (automated). 

Esimtated 3

**Comment by haghighatcs** [comment]
Resolved by #35

**Comment by haghighatcs** [comment]
Resolved by https://github.com/Muzikie/streamer/pull/35
