### ISSUE TITLE
Add support for indexing profile set Attribute command

### ISSUE THREAD

**Issue by reyraa** [Muzikie/service#11]
### Description
As a part of Muzikie/streamer#4, we have to update Service to support the set Attribute command of the profile module.

### Acceptance criteria
Service should be able to 
 - Index transactions of profile: setAttribute
 - List subscriptions 
 - Filter subscriptions by
    - profileID
    - creatorAddress
    - offset
    - count
- The above functionality must be tested (automated). 

Estimated 2

**Comment by haghighatcs** [comment]
resolved by #38
