### ISSUE TITLE
Add support for indexing Collection setAttribute command

### ISSUE THREAD

**Issue by haghighatcs** [Muzikie/service#17]
Description

As a part of #1, we have to update Streamer project to support the SetAttribute (Modify) command of the collection module.
### Acceptance criteria

Service should be able to

- Index transactions of collection:setAttribure
- List collections with the latest updates
- Filter collections by
   - collectionID
   - creatorAddress
   - offset
   - count
- The above functionality must be tested (automated).

**Comment by reyraa** [comment]
Resolved by #25
