### ISSUE TITLE
Enable Service to support the Audio module

### ISSUE THREAD

**Issue by reyraa** [Muzikie/service#2]
### Description

As a step towards Muzikie/streamer#5, Servive can not index transactions of the [Audio module](https://github.com/Muzikie/blockchain/tree/development/src/app/modules/audio) by default. We should add required code base to the Gateway and Indexer micro services to support this module.

### Motivation

Enable Service to support Muzikie modules

### issues
 - #20
 - #22 
 - #28 
 - #30
  - #32
 - #26

**Comment by haghighatcs** [comment]
All the issues are now closed and the epic is completed.
