### ISSUE TITLE
Add support for indexing Collection:Destroy command

### ISSUE THREAD

**Issue by curvesy** [Muzikie/service#27]
### Description

As a part of #1  we have to update Streamer project to support the Destroy command of the collection module.

### Acceptance Criteria

Service should be able to

    Index transactions of collection:destroy
    List of collections without the destroyed one
    Filter collections by
        collectionID
        creatorAddress
        offset
        count
    The above functionality must be tested (automated).

**Comment by haghighatcs** [comment]
Resolved by #34
