### ISSUE TITLE
Enable Service to support the Subscription module

### ISSUE THREAD

**Issue by reyraa** [Muzikie/service#3]
### Description

As a step towards Muzikie/streamer#5, Servive can not index transactions of the [Subscription module](https://github.com/Muzikie/blockchain/tree/development/src/app/modules/subscription) by default. We should add required code base to the Gateway and Indexer micro services to support this module.

### Motivation

Enable Service to support Muzikie modules

### Issues
- Muzikie/streamer#7
- Muzikie/streamer#8
- Muzikie/streamer#9

**Comment by haghighatcs** [comment]
All the tickets have been done
