### ISSUE TITLE
Fix issues discovered with collection transactions indexing mechanism

### ISSUE THREAD

**Issue by haghighatcs** [Muzikie/service#39]
### Description
We have discovered issues with the collection transactions indexing mechanism that we need to fix:

### Improvements required
- Remove event data from the setAttribute, and transfer command tx processor
- Remove the `attributeSet` file
- Remove `updateCollection` function to match the other commands
- Remove blank lines, multiple white spaces and other syntax issues not caught by the linter.

**Comment by reyraa** [comment]
Resolved by #53
