### ISSUE TITLE
Enable Service to support the Profile module

### ISSUE THREAD

**Issue by reyraa** [Muzikie/service#4]
### Description

As a step towards Muzikie/streamer#5, Servive can not index transactions of the [Profile module](https://github.com/Muzikie/blockchain/tree/development/src/app/modules/profile) by default. We should add required code base to the Gateway and Indexer micro services to support this module.

### Motivation

Enable Service to support Muzikie modules

### Issues
 - Muzikie/streamer#10
 - Muzikie/streamer#11

**Comment by haghighatcs** [comment]
All the tickets are done!
