### ISSUE TITLE
Add support of storage of Audio files

### ISSUE THREAD

**Issue by reyraa** [Muzikie/service#40]
### Description
The streamer should be able to store the files corresponding to each transaction to be served in the future.

### Acceptance Criteria
- Streamer should expose an endpoint to post transactions along with files. 
- Once the transaction goes through, the file should be accessible via the NFT ID
- Once the transaction fails to go through, the file should be removed.
- The functionality should be tested

**Comment by haghighatcs** [comment]
We decided to take a different approach and this ticket is no longer valid.
