### ISSUE TITLE
Add support for streaming audio files

### ISSUE THREAD

**Issue by reyraa** [Muzikie/service#41]
### Description
Add an endpoint to stream the audio in chunks.

### Acceptance Criteria
- Users should be able to stream audios that exist
- If any errors occurred, the endpoint should return valid HTTP errors
- If the file exists, the file should be served in chunks
- If the user does not have a valid subscription, it should throw access forbidden
- We should only serve 1 chunk more that consumed.
- If the user fails to submit a corresponding stream transaction after 4 chunks are served, we should stop the streaming with a valid error message
- The functionality should be tested.

**Comment by haghighatcs** [comment]
We decided to take a different approach and this ticket is no longer valid.
