### ISSUE TITLE
Add support for serving profile banner and avatar

### ISSUE THREAD

**Issue by reyraa** [Muzikie/service#42]
### Description

Add an endpoint to serve pictures as static files. The endpoint should have following specifications:

### Acceptance Criteria
- URL:  `profiles/photos`
- Parameters
   - `profileID: string`, required
   - `type: string` An option of `banner` and `avatar`, required.
- Response
    - 200: File return, if the entity exists
    - 404: If the entity does not exist
    - 500: Internal error

**Comment by haghighatcs** [comment]
We decided to take a different approach and this ticket is no longer valid.
