### ISSUE TITLE
Add a dedicated endpoint to serve collection covers

### ISSUE THREAD

**Issue by reyraa** [Muzikie/service#43]
### Description

Add an endpoint to serve pictures as static files. The endpoint should have following specifications:

### Acceptance Criteria
- URL:  `collection/photos`
- Parameters
   - `collectionID: string`, required
- Response
    - 200: File return, if the entity exists
    - 404: If the entity does not exist
    - 500: Internal error

**Comment by haghighatcs** [comment]
We decided to take a different approach and this ticket is no longer valid.
