### ISSUE TITLE
Enable Service to support Muzikie modules

### ISSUE THREAD

**Issue by reyraa** [Muzikie/service#5]
### Description

Our fork of Lisk Service should be able to index and serve all transactions and NFTs of Muzikie. This includes:
 - Collection
 - Audio
 - Subscription
 - Profile

We should make sure the client apps are able to use the date to their purpose. Currently we have Muzikie Web Player waiting to consume this date, soon we'll have Muzikie explorer added to this list.

### Issues
- Muzikie/streamer#1 
- Muzikie/streamer#2 
- Muzikie/streamer#3 
- Muzikie/streamer#4

**Comment by haghighatcs** [comment]
The basic functionality of all the modules are covered and we can consider this epic complete.
